CREATE OR REPLACE FUNCTION verifier_disponibilite_velo(p_idstation INT, p_date TIMESTAMP)
RETURNS BOOLEAN AS $$
DECLARE
    dispo INT;
BEGIN
    SELECT COUNT(*) INTO dispo
    FROM VELO
    WHERE IDSTATION = p_idstation AND EST_DISPONIBLE = TRUE;
    
    RETURN dispo > 0;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION maj_etat_velo()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE VELO
    SET EST_DISPONIBLE = FALSE
    WHERE IDVELO = NEW.IDVELO;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_maj_velo
AFTER INSERT ON VELO_RESERVATION
FOR EACH ROW
EXECUTE FUNCTION maj_etat_velo();
