DROP SEQUENCE IF EXISTS ADRESSE_ID_SEQ CASCADE;
CREATE SEQUENCE ADRESSE_ID_SEQ START 1;
ALTER TABLE ADRESSE
ALTER COLUMN IDADRESSE
SET DEFAULT NEXTVAL('ADRESSE_id_seq');
SELECT SETVAL('ADRESSE_id_seq', 188);
DROP SEQUENCE IF EXISTS CARTE_BANCAIRE_ID_SEQ CASCADE;
CREATE SEQUENCE CARTE_BANCAIRE_ID_SEQ START 1;
ALTER TABLE CARTE_BANCAIRE
ALTER COLUMN IDCB
SET DEFAULT NEXTVAL('CARTE_BANCAIRE_id_seq');
SELECT SETVAL('CARTE_BANCAIRE_id_seq', 10);
DROP SEQUENCE IF EXISTS CATEGORIE_PRODUIT_ID_SEQ CASCADE;
CREATE SEQUENCE CATEGORIE_PRODUIT_ID_SEQ START 1;
ALTER TABLE CATEGORIE_PRODUIT
ALTER COLUMN IDCATEGORIE
SET DEFAULT NEXTVAL('CATEGORIE_PRODUIT_id_seq');
DROP SEQUENCE IF EXISTS CLIENT_ID_SEQ CASCADE;
CREATE SEQUENCE CLIENT_ID_SEQ START 1;
ALTER TABLE CLIENT
ALTER COLUMN IDCLIENT
SET DEFAULT NEXTVAL('CLIENT_id_seq');
SELECT SETVAL('CLIENT_id_seq', 50);
DROP SEQUENCE IF EXISTS CODE_POSTAL_ID_SEQ CASCADE;
CREATE SEQUENCE CODE_POSTAL_ID_SEQ START 1;
ALTER TABLE CODE_POSTAL
ALTER COLUMN IDCODEPOSTAL
SET DEFAULT NEXTVAL('CODE_POSTAL_id_seq');
SELECT SETVAL('CODE_POSTAL_id_seq', 40);
DROP SEQUENCE IF EXISTS COMMANDE_ID_SEQ CASCADE;
CREATE SEQUENCE COMMANDE_ID_SEQ START 1;
ALTER TABLE COMMANDE
ALTER COLUMN IDCOMMANDE
SET DEFAULT NEXTVAL('COMMANDE_id_seq');
DROP SEQUENCE IF EXISTS COURSE_ID_SEQ CASCADE;
CREATE SEQUENCE COURSE_ID_SEQ START 1;
ALTER TABLE COURSE
ALTER COLUMN IDCOURSE
SET DEFAULT NEXTVAL('COURSE_id_seq');
SELECT SETVAL('COURSE_id_seq', 50);
DROP SEQUENCE IF EXISTS COURSIER_ID_SEQ CASCADE;
CREATE SEQUENCE COURSIER_ID_SEQ START 1;
ALTER TABLE COURSIER
ALTER COLUMN IDCOURSIER
SET DEFAULT NEXTVAL('COURSIER_id_seq');
SELECT SETVAL('COURSIER_id_seq', 30);
DROP SEQUENCE IF EXISTS DEPARTEMENT_ID_SEQ CASCADE;
CREATE SEQUENCE DEPARTEMENT_ID_SEQ START 1;
ALTER TABLE DEPARTEMENT
ALTER COLUMN IDDEPARTEMENT
SET DEFAULT NEXTVAL('DEPARTEMENT_id_seq');
DROP SEQUENCE IF EXISTS ENTREPRISE_ID_SEQ CASCADE;
CREATE SEQUENCE ENTREPRISE_ID_SEQ START 1;
ALTER TABLE ENTREPRISE
ALTER COLUMN IDENTREPRISE
SET DEFAULT NEXTVAL('ENTREPRISE_id_seq');
SELECT SETVAL('ENTREPRISE_id_seq', 20);
DROP SEQUENCE IF EXISTS ETABLISSEMENT_ID_SEQ CASCADE;
CREATE SEQUENCE ETABLISSEMENT_ID_SEQ START 1;
ALTER TABLE ETABLISSEMENT
ALTER COLUMN IDETABLISSEMENT
SET DEFAULT NEXTVAL('ETABLISSEMENT_id_seq');
SELECT SETVAL('ETABLISSEMENT_id_seq', 35);
DROP SEQUENCE IF EXISTS FACTURE_COURSE_ID_SEQ CASCADE;
CREATE SEQUENCE FACTURE_COURSE_ID_SEQ START 1;
ALTER TABLE FACTURE_COURSE
ALTER COLUMN IDFACTURE
SET DEFAULT NEXTVAL('FACTURE_COURSE_id_seq');
SELECT SETVAL('FACTURE_COURSE_id_seq', 20);
DROP SEQUENCE IF EXISTS HORAIRES_ID_SEQ CASCADE;
CREATE SEQUENCE HORAIRES_ID_SEQ START 1;
ALTER TABLE HORAIRES
ALTER COLUMN IDHORAIRES
SET DEFAULT NEXTVAL('HORAIRES_id_seq');
DROP SEQUENCE IF EXISTS HORAIRES_COURSIER_ID_SEQ CASCADE;
CREATE SEQUENCE HORAIRES_COURSIER_ID_SEQ START 1;
ALTER TABLE HORAIRES_COURSIER
ALTER COLUMN IDHORAIRES_COURSIER
SET DEFAULT NEXTVAL('HORAIRES_COURSIER_id_seq');
DROP SEQUENCE IF EXISTS PANIER_ID_SEQ CASCADE;
CREATE SEQUENCE PANIER_ID_SEQ START 1;
ALTER TABLE PANIER
ALTER COLUMN IDPANIER
SET DEFAULT NEXTVAL('PANIER_id_seq');
SELECT SETVAL('PANIER_id_seq', 50);
DROP SEQUENCE IF EXISTS PAYS_ID_SEQ CASCADE;
CREATE SEQUENCE PAYS_ID_SEQ START 1;
ALTER TABLE PAYS
ALTER COLUMN IDPAYS
SET DEFAULT NEXTVAL('PAYS_id_seq');
DROP SEQUENCE IF EXISTS PLANNING_RESERVATION_ID_SEQ CASCADE;
CREATE SEQUENCE PLANNING_RESERVATION_ID_SEQ START 1;
ALTER TABLE PLANNING_RESERVATION
ALTER COLUMN IDPLANNING
SET DEFAULT NEXTVAL('PLANNING_RESERVATION_id_seq');
SELECT SETVAL('PLANNING_RESERVATION_id_seq', 50);
DROP SEQUENCE IF EXISTS PRODUIT_ID_SEQ CASCADE;
CREATE SEQUENCE PRODUIT_ID_SEQ START 1;
ALTER TABLE PRODUIT
ALTER COLUMN IDPRODUIT
SET DEFAULT NEXTVAL('PRODUIT_id_seq');
SELECT SETVAL('PRODUIT_id_seq', 118);
DROP SEQUENCE IF EXISTS REGLEMENT_SALAIRE_ID_SEQ CASCADE;
CREATE SEQUENCE REGLEMENT_SALAIRE_ID_SEQ START 1;
ALTER TABLE REGLEMENT_SALAIRE
ALTER COLUMN IDREGLEMENT
SET DEFAULT NEXTVAL('REGLEMENT_SALAIRE_id_seq');
SELECT SETVAL('REGLEMENT_SALAIRE_id_seq', 10);
DROP SEQUENCE IF EXISTS RESERVATION_ID_SEQ CASCADE;
CREATE SEQUENCE RESERVATION_ID_SEQ START 1;
ALTER TABLE RESERVATION
ALTER COLUMN IDRESERVATION
SET DEFAULT NEXTVAL('RESERVATION_id_seq');
SELECT SETVAL('RESERVATION_id_seq', 100);
DROP SEQUENCE IF EXISTS TYPE_PRESTATION_ID_SEQ CASCADE;
CREATE SEQUENCE TYPE_PRESTATION_ID_SEQ START 1;
ALTER TABLE TYPE_PRESTATION
ALTER COLUMN IDPRESTATION
SET DEFAULT NEXTVAL('TYPE_PRESTATION_id_seq');
DROP SEQUENCE IF EXISTS CATEGORIE_PRESTATION_ID_SEQ CASCADE;
CREATE SEQUENCE CATEGORIE_PRESTATION_ID_SEQ START 1;
ALTER TABLE CATEGORIE_PRESTATION
ALTER COLUMN IDCATEGORIEPRESTATION
SET DEFAULT NEXTVAL('CATEGORIE_PRESTATION_id_seq');
DROP SEQUENCE IF EXISTS VEHICULE_ID_SEQ CASCADE;
CREATE SEQUENCE VEHICULE_ID_SEQ START 1;
ALTER TABLE VEHICULE
ALTER COLUMN IDVEHICULE
SET DEFAULT NEXTVAL('VEHICULE_id_seq');
DROP SEQUENCE IF EXISTS VELO_ID_SEQ CASCADE;
CREATE SEQUENCE VELO_ID_SEQ START 1;
ALTER TABLE VELO
ALTER COLUMN IDVELO
SET DEFAULT NEXTVAL('VELO_id_seq');
DROP SEQUENCE IF EXISTS VILLE_ID_SEQ CASCADE;
CREATE SEQUENCE VILLE_ID_SEQ START 1;
ALTER TABLE VILLE
ALTER COLUMN IDVILLE
SET DEFAULT NEXTVAL('VILLE_id_seq');
SELECT SETVAL('VILLE_id_seq', 40);